//이미지 배열
const jobs = {
    "hero": {
        image: "hero.webp",
        skillImage: "angelskill2.png",
        
        aaaa: [
            {
                'text': 'asdawqdsadassdfas',
                'text': 'adhquwdhwqh',
                audio: 'Wineglass On Wood Soft.mp3',
                audio: 'qwjdiwqhj.mp3',
            }
        ]
    },
    "plla": "plla.webp",
    "adel": "adel.png",
    "angel": "angel.png",
    "aran": "aran.png",
    "ark": "ark.png",
    "battle": "battle.png",
    "blas": "blas.png",
    "bow": "bow.png",
    "bye": "bye.png",
    "canon": "canon.png",
    "dark": "dark.webp",
    "demona": "demona.png",
    "demons": "demons.png",
    "dual": "dual.png",
    "eban": "eban.png",
    "frie": "frie.png",
    "god": "god.png",
    "hail": "hail.png",
    "hoyung": "hoyung.png",
    "illi": "illi.png",
    "jenon": "jenon.png",
    "kadena": "kadena.png",
    "kai": "kai.png",
    "kain": "kain.png",
    "kap": "kap.png",
    "kine": "kine.png",
    "lala": "lala.png",
    "lumi": "lumi.png",
    "merse": "merse.png",
    "MKN": "MKN.png",
    "moon": "moon.png",
    "pantom": "pantom.png",
    "path": "path.png",
    "preame": "preame.png",
    "road": "road.png",
    "shadow": "shadow.png",
    "soul": "soul.png",
    "stri": "stri.png",
    "sun": "sun.png",
    "syop": "syop.png",
    "wild": "wild.png",
    "wind": "wind.png",
    "worker": "worker.png",
    "alpa": "alpa.png",
    "beta": "beta.png"
}
const skill = {
    "hero": "hero.webp",
    "plla": "plla.webp",
    "adel": "adel.png",
    "angel": "angel.png",
    "aran": "aran.png",
    "ark": "ark.png",
    "battle": "battle.png",
    "blas": "blas.png",
    "bow": "bow.png",
    "bye": "bye.png",
    "canon": "canon.png",
    "dark": "dark.webp",
    "demona": "demona.png",
    "demons": "demons.png",
    "dual": "dual.png",
    "eban": "eban.png",
    "frie": "frie.png",
    "god": "god.png",
    "hail": "hail.png",
    "hoyung": "hoyung.png",
    "illi": "illi.png",
    "jenon": "jenon.png",
    "kadena": "kadena.png",
    "kai": "kai.png",
    "kain": "kain.png",
    "kap": "kap.png",
    "kine": "kine.png",
    "lala": "lala.png",
    "lumi": "lumi.png",
    "merse": "merse.png",
    "MKN": "MKN.png",
    "moon": "moon.png",
    "pantom": "pantom.png",
    "path": "path.png",
    "preame": "preame.png",
    "road": "road.png",
    "shadow": "shadow.png",
    "soul": "soul.png",
    "stri": "stri.png",
    "sun": "sun.png",
    "syop": "syop.png",
    "wild": "wild.png",
    "wind": "wind.png",
    "worker": "worker.png",
    "alpa": "alpa.png",
    "beta": "beta.png"
}

